### ISSUE TITLE
Test is failing SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by asellappen** [mcmtroffaes/pybtex-docutils#12]
I am trying to run the package on power on cpu arch ppc64le and facing issue in test with invalid synTax
$ pytest --cov-report=xml --cov=pybtex_docutils .
============================= test session starts ==============================
platform linux2 -- Python 2.7.15, pytest-4.6.11, py-1.7.0, pluggy-0.12.0
rootdir: /home/travis/build/asellappen/pybtex-docutils
plugins: cov-2.10.1
collected 3 items / 1 errors / 2 selected                                      
==================================== ERRORS ====================================
____________________ ERROR collecting test/test_backend.py _____________________
../../../../virtualenv/python2.7.15/lib/python2.7/site-packages/_pytest/python.py:507: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
../../../../virtualenv/python2.7.15/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
../../../../virtualenv/python2.7.15/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:304: in load_module
    exec(co, mod.__dict__)
test_backend.py:7: in <module>
    import pybtex.database
E     File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/pybtex/database/__init__.py", line 124
E       f"  entries={repr_entry},\n\n"
E       ^
E   SyntaxError: invalid syntax
---------- coverage: platform linux2, python 2.7.15-final-0 ----------
Coverage XML written to file coverage.xml
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.33 seconds ============================
The command "pytest --cov-report=xml --cov=pybtex_docutils ." exited with 2.
Done. Your build exited with 1.

**Comment by asellappen** [comment]
faining both cpu arch amd64 and ppc64le for the py version 2.7 and 3.5

**Comment by mcmtroffaes** [comment]
This appears to be a bug in pybtex, not in pybtex-docutils?

**Comment by asellappen** [comment]
yes failing at import pybtex.database

**Comment by mcmtroffaes** [comment]
Thanks for confirming. You could report this upstream at pybtex here: https://bitbucket.org/pybtex-devs/pybtex/issues
